# Generated by Django 5.2.8 on 2025-11-15 02:40

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='foto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receta',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nombre', unique=True),
        ),
    ]
