# Generated by Django 5.2.8 on 2025-11-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_alter_receta_foto_alter_receta_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='foto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
